use aerolinea;
drop table fecha;
drop table vuelo;
drop table retraso;
drop table pais;
drop table retraso_vuelo;
drop table vuelo_total;
drop table vuelo_salida;
drop table vuelo_llegada;
drop database aerolinea;
